/*
 http://www.opensource.org/licenses/bsd-license.php New BSD License
 @copyright Copyright (c) 2010, Danny Graham, Scott Thundercloud
*/
var ook={};
ook.Class=function(){var a=function(){var b=this.initialize?this.initialize:this._construct;if(this.__construct){var c=this.__construct.apply(this,arguments);if(b&&c)b.apply(c,arguments);else b&&b.apply(this,arguments);return c?c:this}b&&b.apply(this,arguments)};a.__mixins=[];a.__interfaces=[];a.__extends=null;a.mixin=function(b){this.__mixins.push(b);return this};a.implement=function(b){this.__interfaces.push(b);return this};a.extend=function(b){this.__extends=b;return this};a.prototype.__construct=function(){for(var b=
function(f){f.isDOM=true;f._parent={};try{for(var g in f)if(typeof f[g]=="function")f._parent[g]=f[g];for(g in this)try{f[g]=this[g]}catch(j){}}catch(k){}return f},c=function(f){this._parent=f;for(var g in f)this[g]||(this[g]=this._parent[g]);return this},d=0;d<a.__mixins.length;d++){if(typeof a.__mixins[d]=="function")var e=eval("new "+a.__mixins[d]+"();");else if(typeof a.__mixins[d]=="object")e=a.__mixins[d];if(!e)return;for(var h in e)this[h]=e[h]}if(a.__extends!=null)if(typeof a.__extends!="string")var i=
a.__extends.isDOM||a.__extends.tagName?b.apply(this,[a.__extends]):c.apply(this,[a.__extends]);else if(a.__extends.substring(0,5)!="_DOM_"){d=eval("new "+a.__extends+"();");i=d.isDOM?b.apply(this,[d]):c.apply(this,[d])}else i=b.apply(this,[document.createElement(a.__extends.substring(5))]);return i};return a};ook.mixin=function(a,b){if(typeof b=="function")var c=eval("new "+b+"();");else if(typeof b=="object")c=b;if(!c)return a;for(var d in c)a[d]=c[d];return a};ook.events=ook.Class();
ook.events.prototype._construct=function(){var a={};this.dispatch=function(b,c){if(a[b]){var d=c.type;if(a[b][d])for(var e=0;e<a[b][d].listeners.length;e++)(a[b][d].listeners[e][d]?a[b][d].listeners[e][d]:a[b][d].listeners[e])(c)}};this.addListener=function(b,c,d){a[b]||(a[b]={});a[b][c]||(a[b][c]={name:c,listeners:[]});var e;a:{if(a[b])if(a[b][c]){e=a[b][c].listeners;for(var h=0;h<e.length;h++)if(e[h]==d){e=true;break a}}e=false}e||a[b][c].listeners.push(d)};this.removeListener=function(b,c,d){if(a[b])if(a[b][c])for(var e in a[b][c].listeners)a[b][c].listeners[e]==
d&&a[b][c].listeners.splice(e,1)}};ook.events=new ook.events;ook.observable={dispatch:function(a){ook.events.dispatch(this,a)},addListener:function(a,b){ook.events.addListener(this,a,b)},removeListener:function(a,b){ook.events.removeListener(this,a,b)}};
